// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file v1/api.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/api.proto.
 */
export const file_v1_api: GenFile = /*@__PURE__*/
  fileDesc("Cgx2MS9hcGkucHJvdG8SBmFwaS52MSIfCg9TYXlIZWxsb1JlcXVlc3QSDAoEbmFtZRgBIAEoCSIjChBTYXlIZWxsb1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkyUQoOR3JlZXRlclNlcnZpY2USPwoIU2F5SGVsbG8SFy5hcGkudjEuU2F5SGVsbG9SZXF1ZXN0GhguYXBpLnYxLlNheUhlbGxvUmVzcG9uc2UiAEIkWiJnaXRodWIuY29tL2RhbWVqZXJhcy9qYXJ2aXMvYXBpL3YxYgZwcm90bzM");

/**
 * The request message containing the user's name.
 *
 * @generated from message api.v1.SayHelloRequest
 */
export type SayHelloRequest = Message<"api.v1.SayHelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.SayHelloRequest.
 * Use `create(SayHelloRequestSchema)` to create a new message.
 */
export const SayHelloRequestSchema: GenMessage<SayHelloRequest> = /*@__PURE__*/
  messageDesc(file_v1_api, 0);

/**
 * The response message containing the greetings.
 *
 * @generated from message api.v1.SayHelloResponse
 */
export type SayHelloResponse = Message<"api.v1.SayHelloResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message api.v1.SayHelloResponse.
 * Use `create(SayHelloResponseSchema)` to create a new message.
 */
export const SayHelloResponseSchema: GenMessage<SayHelloResponse> = /*@__PURE__*/
  messageDesc(file_v1_api, 1);

/**
 * The greeter service definition.
 *
 * @generated from service api.v1.GreeterService
 */
export const GreeterService: GenService<{
  /**
   * Sends a greeting
   *
   * @generated from rpc api.v1.GreeterService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof SayHelloRequestSchema;
    output: typeof SayHelloResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_api, 0);

