// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :one
insert into api_keys (id, user_id, name, key_hash, key_prefix, key_suffix, created_at)
values (?, ?, ?, ?, ?, ?, current_timestamp)
returning id, user_id, name, key_hash, key_prefix, key_suffix, created_at, last_used_at
`

type CreateAPIKeyParams struct {
	ID        string
	UserID    int64
	Name      string
	KeyHash   string
	KeyPrefix string
	KeySuffix string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.KeySuffix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeySuffix,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
delete from api_keys
where id = ? and user_id = ?
`

type DeleteAPIKeyParams struct {
	ID     string
	UserID int64
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, arg.ID, arg.UserID)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
select id, user_id, name, key_hash, key_prefix, key_suffix, created_at, last_used_at from api_keys
where key_hash = ?
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeySuffix,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
select id, user_id, name, key_hash, key_prefix, key_suffix, created_at, last_used_at from api_keys
where id = ? and user_id = ?
`

type GetAPIKeyByIDParams struct {
	ID     string
	UserID int64
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeySuffix,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listAPIKeysByUserID = `-- name: ListAPIKeysByUserID :many
select id, user_id, name, key_hash, key_prefix, key_suffix, created_at, last_used_at from api_keys
where user_id = ?
order by created_at desc
`

func (q *Queries) ListAPIKeysByUserID(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.KeySuffix,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
update api_keys
set last_used_at = current_timestamp
where id = ?
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}

const updateAPIKeyName = `-- name: UpdateAPIKeyName :one
update api_keys
set name = ?
where id = ? and user_id = ?
returning id, user_id, name, key_hash, key_prefix, key_suffix, created_at, last_used_at
`

type UpdateAPIKeyNameParams struct {
	Name   string
	ID     string
	UserID int64
}

func (q *Queries) UpdateAPIKeyName(ctx context.Context, arg UpdateAPIKeyNameParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, updateAPIKeyName, arg.Name, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeySuffix,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
