// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID         string
	UserID     int64
	Name       string
	KeyHash    string
	KeyPrefix  string
	KeySuffix  string
	CreatedAt  time.Time
	LastUsedAt sql.NullTime
}

type User struct {
	ID          int64
	Email       string
	GoogleID    sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	LastLoginAt sql.NullTime
	Name        string
}
