// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
insert into users (email, google_id, name) values (?, ?, ?) returning id, email, google_id, created_at, updated_at, last_login_at, name
`

type CreateUserParams struct {
	Email    string
	GoogleID sql.NullString
	Name     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.GoogleID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Name,
	)
	return i, err
}

const findUserByGoogleID = `-- name: FindUserByGoogleID :one
select id, email, google_id, created_at, updated_at, last_login_at, name from users where google_id = ?
`

func (q *Queries) FindUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Name,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, email, google_id, created_at, updated_at, last_login_at, name from users where id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Name,
	)
	return i, err
}

const updateUserLastSeen = `-- name: UpdateUserLastSeen :exec
update users set last_login_at = CURRENT_TIMESTAMP where id = ?
`

func (q *Queries) UpdateUserLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserLastSeen, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
update users set name = ?, last_login_at = CURRENT_TIMESTAMP where id = ?
`

type UpdateUserProfileParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile, arg.Name, arg.ID)
	return err
}
