// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file v1/api.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/api.proto.
 */
export const file_v1_api: GenFile = /*@__PURE__*/
  fileDesc("Cgx2MS9hcGkucHJvdG8SBmFwaS52MSIfCg9TYXlIZWxsb1JlcXVlc3QSDAoEbmFtZRgBIAEoCSIjChBTYXlIZWxsb1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkiJwoMTG9naW5SZXF1ZXN0EhcKD2dvb2dsZV9pZF90b2tlbhgBIAEoCSI4Cg1Mb2dpblJlc3BvbnNlEgsKA2p3dBgBIAEoCRIaCgR1c2VyGAIgASgLMgwuYXBpLnYxLlVzZXIiFwoVR2V0Q3VycmVudFVzZXJSZXF1ZXN0IjQKFkdldEN1cnJlbnRVc2VyUmVzcG9uc2USGgoEdXNlchgBIAEoCzIMLmFwaS52MS5Vc2VyIg8KDUxvZ291dFJlcXVlc3QiIQoOTG9nb3V0UmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCCJCCgRVc2VyEgoKAmlkGAEgASgDEg0KBWVtYWlsGAIgASgJEhEKCWdvb2dsZV9pZBgDIAEoCRIMCgRuYW1lGAQgASgJMlEKDkdyZWV0ZXJTZXJ2aWNlEj8KCFNheUhlbGxvEhcuYXBpLnYxLlNheUhlbGxvUmVxdWVzdBoYLmFwaS52MS5TYXlIZWxsb1Jlc3BvbnNlIgAy0wEKC0F1dGhTZXJ2aWNlEjYKBUxvZ2luEhQuYXBpLnYxLkxvZ2luUmVxdWVzdBoVLmFwaS52MS5Mb2dpblJlc3BvbnNlIgASUQoOR2V0Q3VycmVudFVzZXISHS5hcGkudjEuR2V0Q3VycmVudFVzZXJSZXF1ZXN0Gh4uYXBpLnYxLkdldEN1cnJlbnRVc2VyUmVzcG9uc2UiABI5CgZMb2dvdXQSFS5hcGkudjEuTG9nb3V0UmVxdWVzdBoWLmFwaS52MS5Mb2dvdXRSZXNwb25zZSIAQiNaIWdpdGh1Yi5jb20vZGFtZWplcmFzL2dvb3NlL2FwaS92MWIGcHJvdG8z");

/**
 * The request message containing the user's name.
 *
 * @generated from message api.v1.SayHelloRequest
 */
export type SayHelloRequest = Message<"api.v1.SayHelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.SayHelloRequest.
 * Use `create(SayHelloRequestSchema)` to create a new message.
 */
export const SayHelloRequestSchema: GenMessage<SayHelloRequest> = /*@__PURE__*/
  messageDesc(file_v1_api, 0);

/**
 * The response message containing the greetings.
 *
 * @generated from message api.v1.SayHelloResponse
 */
export type SayHelloResponse = Message<"api.v1.SayHelloResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message api.v1.SayHelloResponse.
 * Use `create(SayHelloResponseSchema)` to create a new message.
 */
export const SayHelloResponseSchema: GenMessage<SayHelloResponse> = /*@__PURE__*/
  messageDesc(file_v1_api, 1);

/**
 * @generated from message api.v1.LoginRequest
 */
export type LoginRequest = Message<"api.v1.LoginRequest"> & {
  /**
   * @generated from field: string google_id_token = 1;
   */
  googleIdToken: string;
};

/**
 * Describes the message api.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_v1_api, 2);

/**
 * @generated from message api.v1.LoginResponse
 */
export type LoginResponse = Message<"api.v1.LoginResponse"> & {
  /**
   * @generated from field: string jwt = 1;
   */
  jwt: string;

  /**
   * @generated from field: api.v1.User user = 2;
   */
  user?: User;
};

/**
 * Describes the message api.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_v1_api, 3);

/**
 * @generated from message api.v1.GetCurrentUserRequest
 */
export type GetCurrentUserRequest = Message<"api.v1.GetCurrentUserRequest"> & {
};

/**
 * Describes the message api.v1.GetCurrentUserRequest.
 * Use `create(GetCurrentUserRequestSchema)` to create a new message.
 */
export const GetCurrentUserRequestSchema: GenMessage<GetCurrentUserRequest> = /*@__PURE__*/
  messageDesc(file_v1_api, 4);

/**
 * @generated from message api.v1.GetCurrentUserResponse
 */
export type GetCurrentUserResponse = Message<"api.v1.GetCurrentUserResponse"> & {
  /**
   * @generated from field: api.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message api.v1.GetCurrentUserResponse.
 * Use `create(GetCurrentUserResponseSchema)` to create a new message.
 */
export const GetCurrentUserResponseSchema: GenMessage<GetCurrentUserResponse> = /*@__PURE__*/
  messageDesc(file_v1_api, 5);

/**
 * @generated from message api.v1.LogoutRequest
 */
export type LogoutRequest = Message<"api.v1.LogoutRequest"> & {
};

/**
 * Describes the message api.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_v1_api, 6);

/**
 * @generated from message api.v1.LogoutResponse
 */
export type LogoutResponse = Message<"api.v1.LogoutResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message api.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_v1_api, 7);

/**
 * @generated from message api.v1.User
 */
export type User = Message<"api.v1.User"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string google_id = 3;
   */
  googleId: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;
};

/**
 * Describes the message api.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_v1_api, 8);

/**
 * The greeter service definition.
 *
 * @generated from service api.v1.GreeterService
 */
export const GreeterService: GenService<{
  /**
   * Sends a greeting
   *
   * @generated from rpc api.v1.GreeterService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof SayHelloRequestSchema;
    output: typeof SayHelloResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_api, 0);

/**
 * Auth service for user authentication
 *
 * @generated from service api.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * Login with Google ID token
   *
   * @generated from rpc api.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Get current authenticated user
   *
   * @generated from rpc api.v1.AuthService.GetCurrentUser
   */
  getCurrentUser: {
    methodKind: "unary";
    input: typeof GetCurrentUserRequestSchema;
    output: typeof GetCurrentUserResponseSchema;
  },
  /**
   * Logout
   *
   * @generated from rpc api.v1.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_api, 1);

