// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file v1/apikey.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_v1_common } from "./common_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/apikey.proto.
 */
export const file_v1_apikey: GenFile = /*@__PURE__*/
  fileDesc("Cg92MS9hcGlrZXkucHJvdG8SBmFwaS52MSKYAQoGQVBJS2V5EgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEgoKa2V5X21hc2tlZBgDIAEoCRIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIwCgxsYXN0X3VzZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIiMKE0NyZWF0ZUFQSUtleVJlcXVlc3QSDAoEbmFtZRgBIAEoCSJtChRDcmVhdGVBUElLZXlSZXNwb25zZRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEgsKA2tleRgDIAEoCRIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCIUChJMaXN0QVBJS2V5c1JlcXVlc3QiNwoTTGlzdEFQSUtleXNSZXNwb25zZRIgCghhcGlfa2V5cxgBIAMoCzIOLmFwaS52MS5BUElLZXkiIQoTRGVsZXRlQVBJS2V5UmVxdWVzdBIKCgJpZBgBIAEoCSInChREZWxldGVBUElLZXlSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIi8KE1VwZGF0ZUFQSUtleVJlcXVlc3QSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCSI3ChRVcGRhdGVBUElLZXlSZXNwb25zZRIfCgdhcGlfa2V5GAEgASgLMg4uYXBpLnYxLkFQSUtleTLAAgoNQVBJS2V5U2VydmljZRJLCgxDcmVhdGVBUElLZXkSGy5hcGkudjEuQ3JlYXRlQVBJS2V5UmVxdWVzdBocLmFwaS52MS5DcmVhdGVBUElLZXlSZXNwb25zZSIAEkgKC0xpc3RBUElLZXlzEhouYXBpLnYxLkxpc3RBUElLZXlzUmVxdWVzdBobLmFwaS52MS5MaXN0QVBJS2V5c1Jlc3BvbnNlIgASSwoMRGVsZXRlQVBJS2V5EhsuYXBpLnYxLkRlbGV0ZUFQSUtleVJlcXVlc3QaHC5hcGkudjEuRGVsZXRlQVBJS2V5UmVzcG9uc2UiABJLCgxVcGRhdGVBUElLZXkSGy5hcGkudjEuVXBkYXRlQVBJS2V5UmVxdWVzdBocLmFwaS52MS5VcGRhdGVBUElLZXlSZXNwb25zZSIAQipaKGdpdGh1Yi5jb20vZGFtZWplcmFzL2dvb3NlL2FwaS9nZW4vZ28vdjFiBnByb3RvMw", [file_v1_common, file_google_protobuf_timestamp]);

/**
 * @generated from message api.v1.APIKey
 */
export type APIKey = Message<"api.v1.APIKey"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Masked version like "gsk_****...****1234"
   *
   * @generated from field: string key_masked = 3;
   */
  keyMasked: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_used_at = 5;
   */
  lastUsedAt?: Timestamp;
};

/**
 * Describes the message api.v1.APIKey.
 * Use `create(APIKeySchema)` to create a new message.
 */
export const APIKeySchema: GenMessage<APIKey> = /*@__PURE__*/
  messageDesc(file_v1_apikey, 0);

/**
 * @generated from message api.v1.CreateAPIKeyRequest
 */
export type CreateAPIKeyRequest = Message<"api.v1.CreateAPIKeyRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.CreateAPIKeyRequest.
 * Use `create(CreateAPIKeyRequestSchema)` to create a new message.
 */
export const CreateAPIKeyRequestSchema: GenMessage<CreateAPIKeyRequest> = /*@__PURE__*/
  messageDesc(file_v1_apikey, 1);

/**
 * @generated from message api.v1.CreateAPIKeyResponse
 */
export type CreateAPIKeyResponse = Message<"api.v1.CreateAPIKeyResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Full unmasked key - only shown once
   *
   * @generated from field: string key = 3;
   */
  key: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message api.v1.CreateAPIKeyResponse.
 * Use `create(CreateAPIKeyResponseSchema)` to create a new message.
 */
export const CreateAPIKeyResponseSchema: GenMessage<CreateAPIKeyResponse> = /*@__PURE__*/
  messageDesc(file_v1_apikey, 2);

/**
 * @generated from message api.v1.ListAPIKeysRequest
 */
export type ListAPIKeysRequest = Message<"api.v1.ListAPIKeysRequest"> & {
};

/**
 * Describes the message api.v1.ListAPIKeysRequest.
 * Use `create(ListAPIKeysRequestSchema)` to create a new message.
 */
export const ListAPIKeysRequestSchema: GenMessage<ListAPIKeysRequest> = /*@__PURE__*/
  messageDesc(file_v1_apikey, 3);

/**
 * @generated from message api.v1.ListAPIKeysResponse
 */
export type ListAPIKeysResponse = Message<"api.v1.ListAPIKeysResponse"> & {
  /**
   * @generated from field: repeated api.v1.APIKey api_keys = 1;
   */
  apiKeys: APIKey[];
};

/**
 * Describes the message api.v1.ListAPIKeysResponse.
 * Use `create(ListAPIKeysResponseSchema)` to create a new message.
 */
export const ListAPIKeysResponseSchema: GenMessage<ListAPIKeysResponse> = /*@__PURE__*/
  messageDesc(file_v1_apikey, 4);

/**
 * @generated from message api.v1.DeleteAPIKeyRequest
 */
export type DeleteAPIKeyRequest = Message<"api.v1.DeleteAPIKeyRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message api.v1.DeleteAPIKeyRequest.
 * Use `create(DeleteAPIKeyRequestSchema)` to create a new message.
 */
export const DeleteAPIKeyRequestSchema: GenMessage<DeleteAPIKeyRequest> = /*@__PURE__*/
  messageDesc(file_v1_apikey, 5);

/**
 * @generated from message api.v1.DeleteAPIKeyResponse
 */
export type DeleteAPIKeyResponse = Message<"api.v1.DeleteAPIKeyResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message api.v1.DeleteAPIKeyResponse.
 * Use `create(DeleteAPIKeyResponseSchema)` to create a new message.
 */
export const DeleteAPIKeyResponseSchema: GenMessage<DeleteAPIKeyResponse> = /*@__PURE__*/
  messageDesc(file_v1_apikey, 6);

/**
 * @generated from message api.v1.UpdateAPIKeyRequest
 */
export type UpdateAPIKeyRequest = Message<"api.v1.UpdateAPIKeyRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message api.v1.UpdateAPIKeyRequest.
 * Use `create(UpdateAPIKeyRequestSchema)` to create a new message.
 */
export const UpdateAPIKeyRequestSchema: GenMessage<UpdateAPIKeyRequest> = /*@__PURE__*/
  messageDesc(file_v1_apikey, 7);

/**
 * @generated from message api.v1.UpdateAPIKeyResponse
 */
export type UpdateAPIKeyResponse = Message<"api.v1.UpdateAPIKeyResponse"> & {
  /**
   * @generated from field: api.v1.APIKey api_key = 1;
   */
  apiKey?: APIKey;
};

/**
 * Describes the message api.v1.UpdateAPIKeyResponse.
 * Use `create(UpdateAPIKeyResponseSchema)` to create a new message.
 */
export const UpdateAPIKeyResponseSchema: GenMessage<UpdateAPIKeyResponse> = /*@__PURE__*/
  messageDesc(file_v1_apikey, 8);

/**
 * API Key service for managing user API keys
 *
 * @generated from service api.v1.APIKeyService
 */
export const APIKeyService: GenService<{
  /**
   * Create a new API key (returns unmasked key)
   *
   * @generated from rpc api.v1.APIKeyService.CreateAPIKey
   */
  createAPIKey: {
    methodKind: "unary";
    input: typeof CreateAPIKeyRequestSchema;
    output: typeof CreateAPIKeyResponseSchema;
  },
  /**
   * List all API keys for the current user (returns masked keys)
   *
   * @generated from rpc api.v1.APIKeyService.ListAPIKeys
   */
  listAPIKeys: {
    methodKind: "unary";
    input: typeof ListAPIKeysRequestSchema;
    output: typeof ListAPIKeysResponseSchema;
  },
  /**
   * Delete an API key
   *
   * @generated from rpc api.v1.APIKeyService.DeleteAPIKey
   */
  deleteAPIKey: {
    methodKind: "unary";
    input: typeof DeleteAPIKeyRequestSchema;
    output: typeof DeleteAPIKeyResponseSchema;
  },
  /**
   * Update an API key (rename only)
   *
   * @generated from rpc api.v1.APIKeyService.UpdateAPIKey
   */
  updateAPIKey: {
    methodKind: "unary";
    input: typeof UpdateAPIKeyRequestSchema;
    output: typeof UpdateAPIKeyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_apikey, 0);

