// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file v1/auth.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "./common_pb";
import { file_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/auth.proto.
 */
export const file_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("Cg12MS9hdXRoLnByb3RvEgZhcGkudjEiJwoMTG9naW5SZXF1ZXN0EhcKD2dvb2dsZV9pZF90b2tlbhgBIAEoCSI4Cg1Mb2dpblJlc3BvbnNlEgsKA2p3dBgBIAEoCRIaCgR1c2VyGAIgASgLMgwuYXBpLnYxLlVzZXIiFwoVR2V0Q3VycmVudFVzZXJSZXF1ZXN0IjQKFkdldEN1cnJlbnRVc2VyUmVzcG9uc2USGgoEdXNlchgBIAEoCzIMLmFwaS52MS5Vc2VyIg8KDUxvZ291dFJlcXVlc3QiIQoOTG9nb3V0UmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCDLTAQoLQXV0aFNlcnZpY2USNgoFTG9naW4SFC5hcGkudjEuTG9naW5SZXF1ZXN0GhUuYXBpLnYxLkxvZ2luUmVzcG9uc2UiABJRCg5HZXRDdXJyZW50VXNlchIdLmFwaS52MS5HZXRDdXJyZW50VXNlclJlcXVlc3QaHi5hcGkudjEuR2V0Q3VycmVudFVzZXJSZXNwb25zZSIAEjkKBkxvZ291dBIVLmFwaS52MS5Mb2dvdXRSZXF1ZXN0GhYuYXBpLnYxLkxvZ291dFJlc3BvbnNlIgBCKlooZ2l0aHViLmNvbS9kYW1lamVyYXMvZ29vc2UvYXBpL2dlbi9nby92MWIGcHJvdG8z", [file_v1_common]);

/**
 * @generated from message api.v1.LoginRequest
 */
export type LoginRequest = Message<"api.v1.LoginRequest"> & {
  /**
   * @generated from field: string google_id_token = 1;
   */
  googleIdToken: string;
};

/**
 * Describes the message api.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_v1_auth, 0);

/**
 * @generated from message api.v1.LoginResponse
 */
export type LoginResponse = Message<"api.v1.LoginResponse"> & {
  /**
   * @generated from field: string jwt = 1;
   */
  jwt: string;

  /**
   * @generated from field: api.v1.User user = 2;
   */
  user?: User;
};

/**
 * Describes the message api.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_v1_auth, 1);

/**
 * @generated from message api.v1.GetCurrentUserRequest
 */
export type GetCurrentUserRequest = Message<"api.v1.GetCurrentUserRequest"> & {
};

/**
 * Describes the message api.v1.GetCurrentUserRequest.
 * Use `create(GetCurrentUserRequestSchema)` to create a new message.
 */
export const GetCurrentUserRequestSchema: GenMessage<GetCurrentUserRequest> = /*@__PURE__*/
  messageDesc(file_v1_auth, 2);

/**
 * @generated from message api.v1.GetCurrentUserResponse
 */
export type GetCurrentUserResponse = Message<"api.v1.GetCurrentUserResponse"> & {
  /**
   * @generated from field: api.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message api.v1.GetCurrentUserResponse.
 * Use `create(GetCurrentUserResponseSchema)` to create a new message.
 */
export const GetCurrentUserResponseSchema: GenMessage<GetCurrentUserResponse> = /*@__PURE__*/
  messageDesc(file_v1_auth, 3);

/**
 * @generated from message api.v1.LogoutRequest
 */
export type LogoutRequest = Message<"api.v1.LogoutRequest"> & {
};

/**
 * Describes the message api.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_v1_auth, 4);

/**
 * @generated from message api.v1.LogoutResponse
 */
export type LogoutResponse = Message<"api.v1.LogoutResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message api.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_v1_auth, 5);

/**
 * Auth service for user authentication
 *
 * @generated from service api.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * Login with Google ID token
   *
   * @generated from rpc api.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Get current authenticated user
   *
   * @generated from rpc api.v1.AuthService.GetCurrentUser
   */
  getCurrentUser: {
    methodKind: "unary";
    input: typeof GetCurrentUserRequestSchema;
    output: typeof GetCurrentUserResponseSchema;
  },
  /**
   * Logout
   *
   * @generated from rpc api.v1.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_auth, 0);

