// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file v1/common.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/common.proto.
 */
export const file_v1_common: GenFile = /*@__PURE__*/
  fileDesc("Cg92MS9jb21tb24ucHJvdG8SBmFwaS52MSJCCgRVc2VyEgoKAmlkGAEgASgDEg0KBWVtYWlsGAIgASgJEhEKCWdvb2dsZV9pZBgDIAEoCRIMCgRuYW1lGAQgASgJQipaKGdpdGh1Yi5jb20vZGFtZWplcmFzL2dvb3NlL2FwaS9nZW4vZ28vdjFiBnByb3RvMw");

/**
 * User represents a user in the system
 *
 * @generated from message api.v1.User
 */
export type User = Message<"api.v1.User"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string google_id = 3;
   */
  googleId: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;
};

/**
 * Describes the message api.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_v1_common, 0);

