// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file v1/greeter.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/greeter.proto.
 */
export const file_v1_greeter: GenFile = /*@__PURE__*/
  fileDesc("ChB2MS9ncmVldGVyLnByb3RvEgZhcGkudjEiHwoPU2F5SGVsbG9SZXF1ZXN0EgwKBG5hbWUYASABKAkiIwoQU2F5SGVsbG9SZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJMlEKDkdyZWV0ZXJTZXJ2aWNlEj8KCFNheUhlbGxvEhcuYXBpLnYxLlNheUhlbGxvUmVxdWVzdBoYLmFwaS52MS5TYXlIZWxsb1Jlc3BvbnNlIgBCKlooZ2l0aHViLmNvbS9kYW1lamVyYXMvZ29vc2UvYXBpL2dlbi9nby92MWIGcHJvdG8z");

/**
 * The request message containing the user's name.
 *
 * @generated from message api.v1.SayHelloRequest
 */
export type SayHelloRequest = Message<"api.v1.SayHelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.SayHelloRequest.
 * Use `create(SayHelloRequestSchema)` to create a new message.
 */
export const SayHelloRequestSchema: GenMessage<SayHelloRequest> = /*@__PURE__*/
  messageDesc(file_v1_greeter, 0);

/**
 * The response message containing the greetings.
 *
 * @generated from message api.v1.SayHelloResponse
 */
export type SayHelloResponse = Message<"api.v1.SayHelloResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message api.v1.SayHelloResponse.
 * Use `create(SayHelloResponseSchema)` to create a new message.
 */
export const SayHelloResponseSchema: GenMessage<SayHelloResponse> = /*@__PURE__*/
  messageDesc(file_v1_greeter, 1);

/**
 * The greeter service definition - example/testing service
 *
 * @generated from service api.v1.GreeterService
 */
export const GreeterService: GenService<{
  /**
   * Sends a greeting
   *
   * @generated from rpc api.v1.GreeterService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof SayHelloRequestSchema;
    output: typeof SayHelloResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_greeter, 0);

